/** React Query cache keys. */
export enum QUERY_KEYS {
  GET_DECLARATIONS_SEARCH = 'GET_DECLARATIONS_SEARCH',
  GET_RANDOM_DECLARATIONS = 'GET_RANDOM_DECLARATIONS',
  GET_STATISTICS = 'GET_STATISTICS',
}
